<a href="https://colab.research.google.com/github/WizardsugarGG/MINERIA-DE-DATOS/blob/main/analisis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

exploracion

In [4]:
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv('Amazon Sale Report.csv', on_bad_lines='skip')
df.info()

/tmp/ipykernel_815/3345108081.py:1: DtypeWarning: Columns (13,15,21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Amazon Sale Report.csv', on_bad_lines='skip')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128973 entries, 0 to 128972
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128973 non-null  int64
 1   Order ID            128973 non-null  object
 2   Date                128973 non-null  object
 3   Status              128973 non-null  object
 4   Fulfilment          128973 non-null  object
 5   Sales Channel       128973 non-null  object
 6   ship-service-level  128973 non-null  object
 7   Style               128973 non-null  object
 8   SKU                 128973 non-null  object
 9   Category            128973 non-null  object
 10  Size                128973 non-null  object
 11  ASIN                128973 non-null  object
 12  Courier Status      122101 non-null  object
 13  Qty                 128973 non-null  object
 14  currency            121178 non-null  object
 15  Amount              121178 non-null  object
 16  ship-city           128939 non-null  object
 17  ship-state          128939 non-null  object
 18  ship-postal-code    128938 non-null  float64
 19  ship-country        128938 non-null  object
 20  promotion-ids       79818 non-null   object
 21  B2B                 128971 non-null  object
 22  fulfilled-by        39274 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: float64(1), int64(1), object(22)
memory usage: 23.6+ MB

In [10]:
#ver la linea que tiene error
with open('Amazon Sale Report.csv') as f:
    for i, line in enumerate(f):
        if i == 7140:
            print(line)

3991,407-6541590-2133933,04-28-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3407,JNE3407-KR-L,kurta,L,B0893DJL8B,Shipped,1,INR,249.0,Kalachowki Mumbai,MAHARASHTRA,400033.0,IN,"Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-SL3Y2YRMAUNFC,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-23LLL7GZCLBVW,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-7X3XCTYG64VBE,Amazon PLCC Free-Financing Universal Merchant AAT-7CHGD3WTS3MHM,Amazon PLCC Free-Financing Universal Merchant AAT-26ZDKNME27X42,Amazon PLCC Free-Financing Universal Merchant AAT-4ZF5KN6E4LJK4,Amazon PLCC Free-Financing Universal Merchant AAT-7RCXIKUAX7DDY,Amazon PLCC Free-Financing Universal Merchant AAT-TNYBHEAO7HOHO,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4,Amazon PLCC Free-Financing Universal Merchant AAT-QMFZ3M7T5NPDS,Amazon PLCC Free-Financing Universal Merchant #MP-pmilan-1601980554292",False,Easy Ship,

In [12]:
#eliminar la ultima columna
df = df.iloc[:, :-1]
df

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,NaN,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,Shipped,1,INR,406.0,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,Shipped,1,INR,329.0,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,NaN,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,Shipped,1,INR,574.0,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128968,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,Shipped,1,INR,517.0,HYDERABAD,TELANGANA,500013.0,IN,NaN,False
128969,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,Shipped,1,INR,999.0,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False
128970,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,Shipped,1,INR,690.0,HYDERABAD,TELANGANA,500049.0,IN,NaN,False
128971,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,Shipped,1,INR,1199.0,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False
128972,128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,...,Shipped,1,INR,696.0,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False

In [15]:
#como saber como se llama las columnas
print(df.columns)

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B'],
      dtype='object')

In [16]:
# Cuenta cuántos True y False hay en total
conteo = df['B2B'].value_counts()
print(conteo)

B2B
False    128100
True        871
Name: count, dtype: int64

In [17]:
#eliminar espacios invisibles
df.columns = df.columns.str.strip()
df

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,NaN,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,Shipped,1,INR,406.0,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,Shipped,1,INR,329.0,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,NaN,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,Shipped,1,INR,574.0,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128968,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,Shipped,1,INR,517.0,HYDERABAD,TELANGANA,500013.0,IN,NaN,False
128969,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,Shipped,1,INR,999.0,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False
128970,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,Shipped,1,INR,690.0,HYDERABAD,TELANGANA,500049.0,IN,NaN,False
128971,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,Shipped,1,INR,1199.0,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False
128972,128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,...,Shipped,1,INR,696.0,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False

2. Identificación del Target (Variable Objetivo)

variables objetivos
Amount → útil para análisis de ingresos y ventas.

Status → útil para análisis logístico y predicción de entregas.

3. Identificación de Variables Numéricas
Las variables cuantitativas clave en tu archivo son:

Qty (Cantidad de productos).

Amount (Precio total).

ship-postal-code (Aunque es numérica, se trata como categoría/geográfica).

4. Análisis de Correlaciones y Selección
Para medir la relación, usamos el coeficiente de Pearson (de -1 a 1).

Variables altamente correlacionadas: Generalmente, Qty y Amount presentan la correlación más alta, ya que a mayor cantidad de productos, mayor es el monto total.

¿Por qué es útil una alta correlación?: Significa que existe una relación lineal fuerte. Si una variable sube y la otra también, el modelo puede usar la variable independiente para predecir con precisión el comportamiento del target.